const copyIcon = `<svg class="copy-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2 2v1"/></svg><svg class="check-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>`;
const smallCopyIcon = `<svg class="detail-copy-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2 2v1"/></svg><svg class="detail-check-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>`;

export const contentTemplate = `
  <section class="content">
    <section id="cepPanel" class="generator-panel">
      <div class="field-group"><label for="stateSearch">Escolha um estado</label><div class="search-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input id="stateSearch" type="search" placeholder="Buscar por nome ou UF..." autocomplete="off" /></div><div id="stateList" class="state-list" role="listbox" aria-label="Estados brasileiros"></div></div>
      <section class="result-card" aria-live="polite"><div class="result-heading"><div><span class="eyebrow">CEP GERADO</span><strong id="selectedState">São Paulo · SP</strong></div><span id="stateBadge" class="state-badge">SP</span></div><div class="cep-row"><span id="generatedCep" class="cep-value">01310-100</span><button id="copyButton" class="icon-button" type="button" title="Copiar CEP" aria-label="Copiar CEP">${copyIcon}</button></div><button id="generateButton" class="primary-button" type="button"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 12a8 8 0 1 1-2.34-5.66M20 4v6h-6"/></svg>Gerar novo CEP</button></section>
      <div class="format-row"><div><strong>Usar formatação</strong><span>Exibir como 00000-000</span></div><label class="switch" aria-label="Alternar formatação do CEP"><input id="formatToggle" type="checkbox" checked /><span></span></label></div>
      <section class="history-section"><div class="section-title"><h2>Gerados recentemente</h2><button id="clearHistory" type="button">Limpar</button></div><div id="historyList" class="history-list"></div></section>
      <section class="custom-section"><div class="section-title"><div><h2>Meus CEPs</h2><span id="customCount">0 salvos</span></div><button id="addCepButton" class="add-button" type="button"><b>+</b> Adicionar</button></div><div id="customList" class="custom-list"></div></section>
    </section>
    <section id="documentsPanel" class="generator-panel" hidden aria-labelledby="documentsTitle"><div class="panel-intro"><h2 id="documentsTitle">Documentos para testes</h2><p>Gere números válidos com dígitos verificadores.</p></div><div id="documentTabs" class="document-tabs" role="group" aria-label="Tipo de documento"><button class="document-tab active" data-document="cpf" type="button">CPF</button><button class="document-tab" data-document="cnpj" type="button">CNPJ</button></div><section class="document-card" aria-live="polite"><div id="documentLabel" class="document-heading">CPF GERADO</div><div class="document-value-row"><output id="documentValue" class="document-value">—</output><button id="documentCopyButton" class="icon-button document-copy" type="button" title="Copiar" aria-label="Copiar resultado">${copyIcon}</button></div><div class="document-format"><div><strong>Usar máscara</strong><span id="documentFormatHint">Exibir como 000.000.000-00</span></div><label class="switch" aria-label="Alternar máscara do documento"><input id="documentFormatToggle" type="checkbox" checked /><span></span></label></div><button id="generateDocumentButton" class="document-generate" type="button">Gerar CPF</button></section></section>
    <section id="cardsPanel" class="generator-panel" hidden aria-labelledby="cardsTitle"><div class="panel-intro"><h2 id="cardsTitle">Cartões para testes</h2><p>Use apenas em ambientes de desenvolvimento.</p></div><div id="cardBrands" class="card-brands" role="group" aria-label="Bandeira do cartão"><button class="card-brand visa selected" data-brand="visa" type="button" aria-label="Visa"><span class="visa-logo">VISA</span></button><button class="card-brand mastercard" data-brand="mastercard" type="button" aria-label="Mastercard"><svg class="mastercard-logo" viewBox="0 0 48 30" aria-hidden="true"><circle cx="17" cy="15" r="12" fill="#eb001b"/><circle cx="31" cy="15" r="12" fill="#f79e1b"/><path d="M24 5.3a12 12 0 0 1 0 19.4 12 12 0 0 1 0-19.4Z" fill="#ff5f00"/></svg></button><button class="card-brand amex" data-brand="amex" type="button" aria-label="American Express"><span class="amex-logo">AMEX</span></button><button class="card-brand discover" data-brand="discover" type="button" aria-label="Discover"><span class="discover-logo">DISCOVER</span></button></div><section class="document-card card-result" aria-live="polite"><div id="cardLabel" class="document-heading">VISA · CARTÃO DE TESTE</div><div class="document-value-row"><output id="cardNumber" class="document-value">—</output><button id="cardCopyButton" class="icon-button document-copy" type="button" title="Copiar cartão" aria-label="Copiar cartão">${copyIcon}</button></div><div class="card-details"><button id="cardExpiryCopyButton" type="button" title="Copiar validade"><span>VALIDADE</span><strong id="cardExpiry">—</strong>${smallCopyIcon}</button><button id="cardCvvCopyButton" type="button" title="Copiar CVV"><span>CVV</span><strong id="cardCvv">—</strong>${smallCopyIcon}</button></div><button id="generateCardButton" class="document-generate" type="button">Gerar novo cartão</button></section></section>
  </section>
`;
